---
name: GitHub OIDC Debug

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print GitHub Context
        run: |
          echo "Repository : ${{ github.repository }}"
          echo "Ref        : ${{ github.ref }}"
          echo "Event      : ${{ github.event_name }}"
          echo "Actor      : ${{ github.actor }}"
          echo "Head Ref   : ${{ github.head_ref }}"
          echo "Base Ref   : ${{ github.base_ref }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::626311400372:role/aws-production-platform-dev-github-actions
          aws-region: ap-south-2

      - name: Verify Identity
        run: |
          aws sts get-caller-identity
