name: Terraform

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Request GitHub OIDC Token
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Event: $GITHUB_EVENT_NAME"

          TOKEN=$(curl -s \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" | jq -r '.value')

          echo "OIDC token successfully requested: ${TOKEN:0:30}..."

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:
          role-to-assume: arn:aws:iam::626311400372:role/aws-production-platform-dev-github-actions
          aws-region: ap-south-2

      - name: Verify AWS Identity
        run: |
          aws --version
          aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color
